import { StatsCards } from "@/components/dashboard/stats-cards"
import { TransactionChart, RiskDistributionChart, FraudPieChart } from "@/components/dashboard/dashboard-charts"
import { RecentAlerts } from "@/components/dashboard/recent-alerts"
import FraudChatbot from "@/components/chat/fraud-chatbot"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Info } from "lucide-react"

export default function DashboardPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Dashboard</h1>
        <p className="text-muted-foreground">AI-powered fraud detection overview</p>
      </div>

      <StatsCards />

      <div className="grid gap-6 lg:grid-cols-4">
        <TransactionChart />
        <RiskDistributionChart />
        <FraudPieChart />
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <RecentAlerts />
          <Card className="border-border bg-card border-primary/25 shadow-[0_0_18px_rgba(59,130,246,0.18)]">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Info className="h-4 w-4 text-primary" />
                Risk Score Explanation
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-muted-foreground">
              <p>
                Risk scores are generated by combining behavior signals from transaction patterns and account profile anomalies.
              </p>
              <p>
                Primary inputs include transaction velocity, repeated near-threshold amounts (structuring), circular fund flow loops,
                dormant account reactivation, unusual geolocation/IP behavior, and shell-entity linkage.
              </p>
              <p>
                Final score bands: <span className="text-success">0-39 Low</span>,{" "}
                <span className="text-warning">40-79 Suspicious</span>,{" "}
                <span className="text-destructive">80+ Flagged</span>.
              </p>
            </CardContent>
          </Card>
        </div>
        <div className="lg:col-span-1">
          <FraudChatbot />
        </div>
      </div>
    </div>
  )
}
